version: "3"
services:
  pygeoapi:
    image: geopython/pygeoapi:latest
    container_name: pygeoapi_indg-20-60
    volumes:
      - ./my.config.yml:/pygeoapi/local.config.yml
      #- ./data:/pygeoapi/tests/data
    ports:
      - "5000:80"

