# =================================================================
#
# Authors: Maxime Collombin <maxime.collombin@heig-vd.ch>
#
# Copyright (c) 2022 Maxime Collombin
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================
# Server connection settings
server:
    bind:
        host: 0.0.0.0
        port: 5000
    url: http://localhost:5000/
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    gzip: false
    languages:
        # First language is the default language
        - en-US
        - fr-CA
    cors: true
    pretty_print: true
    limit: 10
    # templates: /path/to/templates
    map:
        url: https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png
        attribution: '<a href="https://wikimediafoundation.org/wiki/Maps_Terms_of_Use">Wikimedia maps</a> | Map data &copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
    manager:
        name: TinyDB
        connection: /tmp/pygeoapi-test-process-manager.db
        output_dir: /tmp
# Logging        
logging:
    level: ERROR
    #logfile: /tmp/pygeoapi.log
# Metadata
metadata:
    identification:
        title:
            en: ngdi-20-60 
            fr: indg-20-60
        description:
            en: pygeoapi demo instance
            fr: instsance de démo pygeoapi 
        keywords:
            en:
                - geospatial
                - data
                - api
            fr:
                - géospatiale
                - données
                - api
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: http://example.org
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: Media Engineering Institute (MEI)
        url: https://heig-vd.ch/rad/instituts/mei
    contact:
        name: Lastname, Firstname
        position: Position Title
        address: Avenue des Sports 20, Case postale 521
        city: Yverdon-les-Bains
        stateorprovince: Vaud
        postalcode: 1401 
        country: Switzerland
        phone: +xx-xxx-xxx-xxxx
        fax: +xx-xxx-xxx-xxxx
        email: maxime.collombin@heig-vd.ch
        url: https://heig-vd.ch/rad/instituts/mei
        hours: Hours of Service
        instructions: During hours of service.  Off on weekends.
        role: pointOfContact
# Ressources:
resources:
    # Collection # 1: dummy data (*.csv provider)
    obs:
        type: collection
        title:
            en: Observations
            fr: Observations
        description:
            en: My cool observations
            fr: Mes belles observations
        keywords:
            - observations
            - monitoring
        links:
            - type: text/csv
              rel: canonical
              title: data
              href: https://github.com/mapserver/mapserver/blob/branch-7-0/msautotest/wxs/data/obs.csv
              hreflang: en-US
            - type: text/csv
              rel: alternate
              title: data
              href: https://raw.githubusercontent.com/mapserver/mapserver/branch-7-0/msautotest/wxs/data/obs.csv
              hreflang: en-US
        context:
            - schema: https://schema.org/
              stn_id:
                "@id": schema:identifier
                "@type": schema:Text
              datetime:
                "@type": schema:DateTime
                "@id": schema:observationDate
              value:
                "@type": schema:Number
                "@id": schema:QuantitativeValue
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 2000-10-30T18:24:39Z
                end: 2007-10-30T08:57:29Z
                trs: http://www.opengis.net/def/uom/ISO-8601/0/Gregorian
        providers:
            - type: feature
              name: CSV
              data: tests/data/obs.csv
              id_field: id
              geometry:
                  x_field: long
                  y_field: lat
    # Collection # 2: larges lakes (mapbox-vector-tile)
    lakes:
        type: collection
        title:
            en: Large Lakes
            fr: Grands Lacs
        description:
            en: lakes of the world, public domain
            fr: lacs du monde, domaine public
        keywords:
            - lakes
        links:
            - type: text/html
              rel: canonical
              title: information
              href: http://www.naturalearthdata.com/
              hreflang: en-US
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 2011-11-11T11:11:11Z
                end: null  # or empty (either means open ended)
        providers:
            # - type: feature
            #   name: GeoJSON
            #   data: tests/data/ne_110m_lakes.geojson
            #   id_field: id
            - type: tile
              name: MVT
              # data: http://localhost:9000/ne_110m_lakes/{z}/{x}/{y}
              data: tests/data/tiles/ne_110m_lakes
              options:
                metadata_format: raw # default | tilejson
                bounds: [[-124.953634,-16.536406],[109.929807,66.969298]]
                zoom:
                    min: 0
                    max: 11
                schemes:
                    - WorldCRS84Quad
              format: 
                    name: pbf
                    mimetype: application/vnd.mapbox-vector-tile
    # Collection # 3: exploitations agricoles WFS (OGR WFS provider) 
    exploitation_agricole:
        type: collection
        title: 'Exploitation agricole: Surfaces d’utilisation'
        description: Les surfaces d’utilisation correspondent aux surfaces agricoles selon l’ordonnance sur la terminologie agricole (OTerm), l’ordonnance sur les paiements directs et la définition des utilisations qui en découle et dont se servent la Confédération et les cantons. Les données sont conformes au MGDM surfaces d’utilisation (ID 153.1, Version 1.4).
        keywords:
            - Switzerland
            - Agriculture
            - IFDG
            - Geodienste.ch
            - WFS
        crs:
            - CRS84
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://geodienste.ch/services/lwb_nutzungsflaechen
            #   other useful links:
            #   https://geodienste.ch/db/lwb_nutzungsflaechen_0/fra?SERVICE=WFS&REQUEST=GetCapabilities
            #   https://geodienste.ch/db/lwb_nutzungsflaechen_0/fra?version=2.0.0&request=describeFeatureType
              hreflang: fr-CH
        extents:
            spatial:
                bbox: [5.96,45.82,10.49,47.81] # Area of interest (min Long, min Lat, max Long, max Lat)
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin:
                end: null  # or empty
        providers:
            - type: feature
              name: OGR
              data:
                  source_type: WFS
                  source: WFS:https://wfs.geodienste.ch/lwb_nutzungsflaechen_0/fra?
                  source_srs: EPSG:2056
                  target_srs: EPSG:4326
                  source_capabilities:
                      paging: True
                  source_options:
                    #   OGR_WFS_VERSION: 2.0.0
                      OGR_WFS_LOAD_MULTIPLE_LAYER_DEFN: NO
                  gdal_ogr_options:
                      EMPTY_AS_NULL: NO
                      GDAL_CACHEMAX: 64
                      # GDAL_HTTP_PROXY: (optional proxy)
                      # GDAL_PROXY_AUTH: (optional auth for remote WFS)
                      CPL_DEBUG: NO
              id_field: t_id
              layer: ms:nutzungsflaechen
    # Process # 1
    hello-world:
        type: process
        processor:
            name: HelloWorld
